# Generated by Django 2.2.7 on 2019-11-24 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MovieInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mname', models.CharField(max_length=200)),
                ('years', models.CharField(max_length=20)),
                ('score', models.CharField(max_length=20)),
                ('director', models.CharField(max_length=1000)),
                ('mold', models.CharField(max_length=200)),
                ('act', models.CharField(max_length=1000)),
                ('languages', models.CharField(max_length=200)),
                ('img', models.CharField(max_length=200)),
                ('details', models.CharField(max_length=200)),
                ('official', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='UserAdmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
    ]
