# Generated by Django 2.2.7 on 2019-11-29 06:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MovieBackgrounds', '0002_movietop'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movieinformation',
            options={'verbose_name': '电影信息', 'verbose_name_plural': '电影信息'},
        ),
        migrations.AlterModelOptions(
            name='movietop',
            options={'verbose_name': '电影排行', 'verbose_name_plural': '电影排行'},
        ),
        migrations.AlterModelOptions(
            name='useradmin',
            options={'verbose_name': '用户', 'verbose_name_plural': '用户'},
        ),
        migrations.AlterField(
            model_name='movieinformation',
            name='act',
            field=models.CharField(max_length=1000, verbose_name='演员'),
        ),
        migrations.AlterField(
            model_name='movieinformation',
            name='details',
            field=models.CharField(max_length=200, verbose_name='电影详情'),
        ),
        migrations.AlterField(
            model_name='movieinformation',
            name='director',
            field=models.CharField(max_length=1000, verbose_name='导演'),
        ),
        migrations.AlterField(
            model_name='movieinformation',
            name='img',
            field=models.CharField(max_length=200, verbose_name='电影图片地址'),
        ),
        migrations.AlterField(
            model_name='movieinformation',
            name='languages',
            field=models.CharField(max_length=200, verbose_name='语言'),
        ),
        migrations.AlterField(
            model_name='movieinformation',
            name='mname',
            field=models.CharField(max_length=200, verbose_name='电影名称'),
        ),
        migrations.AlterField(
            model_name='movieinformation',
            name='mold',
            field=models.CharField(max_length=200, verbose_name='类型'),
        ),
        migrations.AlterField(
            model_name='movieinformation',
            name='official',
            field=models.CharField(max_length=200, verbose_name='电影官方网址'),
        ),
        migrations.AlterField(
            model_name='movieinformation',
            name='score',
            field=models.CharField(max_length=20, verbose_name='评分'),
        ),
        migrations.AlterField(
            model_name='movieinformation',
            name='years',
            field=models.CharField(max_length=20, verbose_name='年份'),
        ),
        migrations.AlterField(
            model_name='movietop',
            name='act',
            field=models.CharField(max_length=1000, verbose_name='演员'),
        ),
        migrations.AlterField(
            model_name='movietop',
            name='details',
            field=models.CharField(max_length=200, verbose_name='电影详情'),
        ),
        migrations.AlterField(
            model_name='movietop',
            name='director',
            field=models.CharField(max_length=1000, verbose_name='导演'),
        ),
        migrations.AlterField(
            model_name='movietop',
            name='img',
            field=models.CharField(max_length=200, verbose_name='电影图片地址'),
        ),
        migrations.AlterField(
            model_name='movietop',
            name='mname',
            field=models.CharField(max_length=200, verbose_name='电影名称'),
        ),
        migrations.AlterField(
            model_name='movietop',
            name='mold',
            field=models.CharField(max_length=200, verbose_name='类型'),
        ),
        migrations.AlterField(
            model_name='movietop',
            name='score',
            field=models.CharField(max_length=20, verbose_name='评分'),
        ),
        migrations.AlterField(
            model_name='movietop',
            name='years',
            field=models.CharField(max_length=20, verbose_name='年份'),
        ),
        migrations.AlterField(
            model_name='useradmin',
            name='password',
            field=models.CharField(max_length=20, verbose_name='密码'),
        ),
        migrations.AlterField(
            model_name='useradmin',
            name='username',
            field=models.CharField(max_length=20, verbose_name='用户名'),
        ),
        migrations.CreateModel(
            name='MovieCollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MovieBackgrounds.MovieInformation')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
